# Service - LoadBalancer
# # pb-service -lb.yml
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    app: petclinic-app
spec:
  selector:
    app: petclinic-app
  type: LoadBalancer
  ports:
  - nodePort: 32751
    port: 8080
    targetPort: 8080
# NodePort not necessary as we are using ELB
# This gives additional access option using <ip_of_node>:32751
